### ISSUE TITLE
Add support for later versions of emoji and awesome font

### ISSUE THREAD

**Issue by uw0wu** [joshmcrty/Flurry#12]
Please add support for later versions of emoji and awesome font.
Or tell me how to add.

**Comment by uw0wu** [comment]
These icon sets are not displayed (Example):

🎄🎅  🌨️ 🎁 🧊 🔔 ⛷️ 🏂 🧤 🧦
🛍 💲 💰︎ 🪙 💵 💶 💷 💴 💳 💸 🤑 🎁 🧳 📦

    Font Awesome 4
    <i class="fa fa-snowflake-o"></i>
    <i class="fa fa-music"></i>
    <i class="fa fa-bell-o"></i>
    <i class="fa fa-diamond"></i>
    <i class="fa fa-gift"></i>

**Comment by joshmcrty** [comment]
This should be resolved now with https://github.com/joshmcrty/Flurry/releases/tag/1.2.0. The `character` setting should now be passed an array of characters to avoid emoji issues. See the updated [examples](https://joshmcrty.github.io/Flurry/) for this change and a potential solution to use FontAwesome. The [readme](https://github.com/joshmcrty/Flurry) has also been updated with the new `onFlake` hook.
